### ISSUE TITLE
Dartling Gunner 030 not working with AdditionalTiers (1.4 and 1.3)

### ISSUE THREAD

**Issue by davida1a2** [1330-Studios/BTD6E-Modules#1]
Dartling Gunner middle path above 2 is not shooting any projectiles. 
Using only BTD6 Mod Helper 2.1.
Testet in playthrough and in sandbox (logfile is testing in sandbox).

When more mods are used, more towers don't work. E.g. Mechanic bottom Path above 2 or Heli pad. 
Am I missing a dependency? (Sorry for my english)
[Latest.log](https://github.com/1330-Studios/BTD6E-Modules/files/7170023/Latest.log)

**Comment by davida1a2** [comment]
Log only using AdditionalTiers (No ModHelper):
[Latest.log](https://github.com/1330-Studios/BTD6E-Modules/files/7170133/Latest.log)

**Comment by KosmicShovel** [comment]
Fixed by [this](https://github.com/1330-Studios/BTD6E-Modules/commit/1be64626cd7953e4aa8acde60d6a925d957c42d2) Commit, thanks for bringing this to my attention!
