### ISSUE TITLE
A lot of bugs

### ISSUE THREAD

**Issue by The-Ultimate-Dart-Monkey** [1330-Studios/BTD6E-Modules#2]
hello there are issues with additionaltiers and godlytowers they just don't load and break the game pls fix

**Comment by The-Ultimate-Dart-Monkey** [comment]
[MelonLoader_21-10-30_10-47-47.836.log](https://github.com/1330-Studios/BTD6E-Modules/files/7446924/MelonLoader_21-10-30_10-47-47.836.log)

**Comment by KosmicShovel** [comment]
Should work now with the 1.5 Update.

**Comment by The-Ultimate-Dart-Monkey** [comment]
ok thx
